#! /bin/bash
echo " Maintainer Prakash Poudel"
sudo yum update -y && yum install wget -y
sudo mkdir /app && cd /app
sudo wget https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.2-02-unix.tar.gz
sudo tar -xvf nexus-3.0.2-02-unix.tar.gz && sudo mv nexus-3.0.2-02 nexus && rm nexus*.tar.gz
sudo adduser nexus && sudo chown -R nexus:nexus /app/nexus
run_as_user="nexus"
sudo ln -s /app/nexus/bin/nexus /etc/init.d/nexus
sudo chkconfig --add nexus
sudo chkconfig --levels 345 nexus on
sudo service nexus start
echo "check your port /8081"
echo "User Name: admin Password: admin123"
